### ISSUE TITLE
Set the 'immutable' Cache-Control directive for long-lived static assets

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-web#1371]
Firefox/Edge/Safari TP support a new Cache-Control `immutable` directive which prevents superfluous requests for long lived static assets.

Currently assets served from cdn.travis-ci.org are served with the header:
```
Cache-Control: public, max-age=31536000
```

This means that when say visiting https://travis-ci.org/profile/mozilla in Firefox/Edge and then hitting F5 (note, not ctrl+F5 for a force refresh - that intentionally always re-fetches everything), new HTTP 304s are seen for the fingerprinted assets that had a 1 year expiry and so did not need to be refetched, such as:
https://cdn.travis-ci.org/assets/vendor-8a29ab60ba44e825e9299cc7598ca2b0.css

Changing the reponse header to include `immutable` would prevent these unnecessary requests, ie:
```
Cache-Control: public, max-age=31536000, immutable
```

For further reading, see:
https://bitsup.blogspot.co.uk/2016/05/cache-control-immutable.html
https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/
https://tools.ietf.org/html/draft-mcmanus-immutable-00
https://code.facebook.com/posts/557147474482256/this-browser-tweak-saved-60-of-requests-to-facebook/
https://www.keycdn.com/blog/cache-control-immutable/

**Comment by BanzaiMan** [comment]
@edmorley As you saw in ISSUE_TEMPLATE, this is not a place for reports of this kind. Please reopen this in https://github.com/travis-ci/travis-ci/issues. Thanks.

**Comment by edmorley** [comment]
Ok, it's just the ISSUE_TEMPLATE reads as "not the place for general bug reports about travis" - whereas this ticket is specific to travis-web's setting of Cache-Control headers, for which I was about to open a PR.

If the intent is to not have any issues here at all - perhaps issues should be disabled? :-)
