### ISSUE TITLE
Duplicate API call made to statuspage.io API on initial pageload

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-web#1372]
**STR:**
1. Open a new tab in Firefox Nightly
2. Open the developer console to the networking panel
3. Navigate the tab to https://travis-ci.org/profile/mozilla

**Expected:**
Only one call to the statuspage.io API on initial pageload.

**Actual:**
Two identical calls to the statuspage.io API:
https://pnpcptp8xh9k.statuspage.io/api/v2/status.json
...with the first receiving an HTTP 200 response, and the second an HTTP 304.

**Comment by BanzaiMan** [comment]
@edmorley As you saw in ISSUE_TEMPLATE, this is not a place for reports of this kind. Please reopen this in https://github.com/travis-ci/travis-ci/issues. Thanks.
