### ISSUE TITLE
travis-ci.org should show some information about Travis to a not-logged-in user

### ISSUE THREAD

**Issue by tay** [travis-ci/travis-web#177]
Currently, when a user who's not logged in browses the travis site, the main panel displays a random build (the most recent build). The call-to-action to create a new account is hidden in the top right corner.

![Travis Home Page](https://f.cloud.github.com/assets/1108361/423990/093d45e6-ad79-11e2-9fe8-084cc8707542.png)

To me this is pretty bad. This page is the public face of our project, this is the first thing people see when they get to Travis from Googling 'Travis CI'. It can't just be a slight variant on the logged-in user dashboard, it needs to show more information about Travis.

Here are some examples of other home pages:
![Facebook Home Page](https://f.cloud.github.com/assets/1108361/424005/c5bc2e8a-ad79-11e2-9c2a-84d1581178f1.png)

![Github Home Page](https://f.cloud.github.com/assets/1108361/424003/bc7df4a2-ad79-11e2-8e4c-e01e00efdff3.png)

**Comment by joshk** [comment]
Closing as we have a new (long overdue) landing page ready for next week.
