### ISSUE TITLE
Feedback & support link obscures link to top

### ISSUE THREAD

**Issue by BM5k** [travis-ci/travis-web#278]
This occurs with the right sidebar collapsed.

![bni1cexigaanxeh png-large](https://cloud.githubusercontent.com/assets/29762/2974582/d0457588-db8a-11e3-9e3e-1a8f2b3a11ba.png)

OSX 10.9.2, Safari Version 7.0.3 (9537.75.14)

**Comment by joshk** [comment]
Closing for now as this has become stale.

If it is still an issue please let us know and we will dive into it.

**Comment by BM5k** [comment]
This appears to have been fixed, thanks!
