### ISSUE TITLE
Create landing page for users not logged in

### ISSUE THREAD

**Issue by saltinejustine** [travis-ci/travis-web#293]
We've discussed the need for a landing page/explanation when first time users or users not logged in to see when they go to travis-ci.org.

We can start off with welcome text to say something along the lines of,
"Hey there, looks like this is your first time here."
In addition some copy below that says,
"Already a user? Please sign in"

What all would we like to include on this page in addition to copy like this?

Short explanation of what travis is? More descriptive? Images of the product?

**Comment by joshk** [comment]
Closing as we finally have something in the works.

Me so excited!
