### ISSUE TITLE
Feature request - support request parameter '?branch=param' to filter the list based on the param

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-web#300]
Currently all these three URLs do not accept request parameter:
https://travis-ci.org/urho3d/Urho3D/builds
https://travis-ci.org/urho3d/Urho3D/pull_requests
https://travis-ci.org/urho3d/Urho3D/branches
So they returns a list of the past builds from all the branches. It would be great if we can pass the ``branch``` request parameter to filter the list just to return the past builds for a particular branch, especially for repository that uses long-running branches with CI build.

As an example use case, this is the [website](http://urho3d.github.io/) of our project which uses Travis CI build status image from two of our long-running branches. The two ```<img>``` tags are wrapped inside an ```<a>``` tag with href attribute set to ```https://travis-ci.org/urho3d/Urho3D/builds``` because at the moment there is no way to show two separate list for each branch, such as:
https://travis-ci.org/urho3d/Urho3D/builds?branch=master
https://travis-ci.org/urho3d/Urho3D/builds?branch=OSX-CI

**Comment by joshk** [comment]
Closing as this has become a little stale and is likely to be included in our V3 API.
