### ISSUE TITLE
Shouldn't break with Blender

### ISSUE THREAD

**Issue by muchweb** [travis-ci/travis-web#303]
After preloaders are displayed, website is freezing (looks like javascript has crashed). It freezes right before displaying lists of repos.

It seems to break with [Blender](https://github.com/meh/blender) extension switched on (Blender is rewriting browser headers to the most the common in order to 'blend with a crowd').

This is the only site that I have experienced this problem with. This seems very odd. It shouldn't break.

Is the webiste running any "windows"-specific code?

---
I am using GNU operating system and Firefox 32.0.1.

**Comment by joshk** [comment]
We are not running Rails.

Are you still experiencing this issue?

**Comment by muchweb** [comment]
@joshk, it now works with `Accept-Charset: *`. I assume that it is extension problem that is rewriting accept headers priority.
