### ISSUE TITLE
Travis CI web interface does not get rendered correctly anymore on mobile Safari browsers.

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-web#305]
Not sure whether it is caused by the recent iOS 8 upgrade or there were some changes on travis-web side recently, the CI build web page does not get rendered correctly anymore on my iPad's or iPhone's mobile Safari browser. It was perfectly OK before.

The web interface still functions as before on Desktop Safari browser.

**Comment by joshk** [comment]
This should be fixed now. Closing.
