### ISSUE TITLE
UI: easier canceling a build

### ISSUE THREAD

**Issue by brownman** [travis-ci/travis-web#317]
needed:
- a 'cancel-this-build' button

where:
- on the list of all running(ongoing) builds

why:
- when using github as editor OR any other online editor which integrates with github:
- every file save creates a new build !
- there is no easy way to cancel all the build - but Enter each of the builds and press on cancel.

situation:
- a user has to do changes in 10 files for creating a new successful test => he has to wait for 10 builds until his test will actually get proccessed !

**Comment by joshk** [comment]
Gonna close this as we have something in the works.

Many High 5s
