### ISSUE TITLE
Long ENV string causes parts of build matrix to be hidden

### ISSUE THREAD

**Issue by cottrell** [travis-ci/travis-web#320]
Not sure if this is the right place to post. Please let me know if there is a more useful place to mention this.

Information such as the build version is not viewable in the build matrix on smaller screens (such as macbook).

Large window:
![screenshot 2014-12-28 11 34 41](https://cloud.githubusercontent.com/assets/223276/5563736/9f902290-8e85-11e4-90bf-d643e538b93f.png)

Small window:
![screenshot 2014-12-28 11 35 50](https://cloud.githubusercontent.com/assets/223276/5563743/e992a962-8e85-11e4-9435-55bc2f2e8487.png)

On OSX, Google Chrome 39.0.2171.95 (64-bit)

**Comment by joshk** [comment]
Closing as we have some new UI changes in the works which will be deployed this week to help solve this

**Comment by GBH** [comment]
New UI changes don't show Gemsets anymore. So now my matrix just shows ruby versions. Not super useful.

**Comment by joshk** [comment]
Can you please open a new issue and we can look into getting this fixed.
