### ISSUE TITLE
Incorrect spacing before "✔" in console output (with mocha tests)

### ISSUE THREAD

**Issue by sabhiram** [travis-ci/travis-web#321]
When mocha test groups are nested, the console output in the `<pre> #log.ansi` element is incorrect.

Here is a build which shows off the issue:
https://travis-ci.org/sabhiram/raspberry-pimage/builds/45321036

Notice the ignored tests (leading with a `-`) are spaced further in the output than the nested passing tests.

Here is the expected output:
![expectedoutput](https://cloud.githubusercontent.com/assets/2693144/5566025/7457ab80-8eca-11e4-8c74-41d61fac2c30.png)

My guess is that the "✔" char is being matched and replaced blindly by the `<span>✔</span>` element with a fixed amount of space.

Super minor issue, but my OCD gets the better of me :)

**Comment by joshk** [comment]
I'm going to close this issue as it has become stale.

If you are still interested in helping please reopen it at travis-ci/travis-ci

Thanks!
