### ISSUE TITLE
Settings tab is visible only when it is chosen from the cog menu

### ISSUE THREAD

**Issue by zzak** [travis-ci/travis-web#322]
See attached gif:

![travis-settings-ui-bug](https://cloud.githubusercontent.com/assets/277819/5618881/d2086c80-94d1-11e4-8287-9190f09a13ed.gif)

cc @saltinejustine

**Comment by rkh** [comment]
This is not entirely a glitch. The main issue here is that what's up there isn't really tabs, but a single path in a tree of nested pages (see tabs when looking at a build/job). For this reason we have concrete plans to move away from the tabs metaphor.

**Comment by zzak** [comment]
@rkh What is a tab really?

**Comment by saltinejustine** [comment]
@zzak 

![](http://vikingcocacola.com/files/cache/4444226cb99d6ff6ed1ff58c91a620ad_f138.png)

**Comment by zzak** [comment]
@saltinejustine Are you sure its not this one?
![tab_key](https://cloud.githubusercontent.com/assets/277819/5635835/8eb3371e-95a1-11e4-9e3d-edc9653f9f14.png)

**Comment by joshk** [comment]
:heart:
