### ISSUE TITLE
Travis-ci not render correctly on Chrome

### ISSUE THREAD

**Issue by ldonnet** [travis-ci/travis-web#325]
Is use travis-ci for a while and thanks for these amazing services!
I encounter a render error when I go to travis-ci on Chrome Version 39.0.2171.95 (64-bit) on Debian 8.
We arrive on a blank page and we must scroll to access to travis web app. You could see that in the screen capture.
![travis ci free hosted continuous integration platform for the open source community](https://cloud.githubusercontent.com/assets/314537/5718514/f35c0b7e-9b0e-11e4-85c7-194845fa9f44.png)

**Comment by drogus** [comment]
@ldonnet I can't reproduce it on both Mac OSX and Ubuntu and I'm not sure if there will be any difference between Ubuntu and Debian so I have a few questions/requests:

1. Does it happen also when you're logged out?
2. Could you try to reproduce it in the Incognito Mode?
3. Could you try it on a different profile, ie. without any extensions installed? (unless you don't use any extensions)
4. Could you try to clear cache and cookies for travis-ci.org domain?
5. Does it look like that every time you refresh a page?

**Comment by ldonnet** [comment]
It happens : 
*  when I'm logged out 
* when I clear cache
* when I refresh page 

When I'm in incognito mode it isn't happened. And I havn't a javascript error like in normal mode :  
Mixed Content: The page at 'https://travis-ci.org/recent' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://66.228.34.50/js/chromeServerV45.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by BanzaiMan** [comment]
If it doesn't happen in incongnito mode, perhaps a Chrome extension is interfering.

**Comment by ldonnet** [comment]
Hi,

I test all my extension and you are right it fails with an old one that doesn't exist anymore.

Thanks for your help
