### ISSUE TITLE
No color diagnostic output in the log

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-web#337]
All the sudden the color diagnostic output from GNU and Clang compilers are not displayed anymore in the logs. It was still OK a few hours ago.

**Comment by BanzaiMan** [comment]
Could you point to a build log URL that shows this problem?

**Comment by weitjong** [comment]
At the time I wrote this issue, the problem exists in all the build log histories. However, soon after I created this issue, the problem seems to be resolved already. Cheers.
