### ISSUE TITLE
Project Settings Page Concurrent Job Input Pattern

### ISSUE THREAD

**Issue by tankerkiller125** [travis-ci/travis-web#338]
The Input Pattern currently being used on the Cuncurrent Job input is incorrect. You currently have it set as: pattern="/^[0-9]+$/" However it should be: pattern="^[0-9]+$"

Edit the URL for that line of code is found at https://github.com/travis-ci/travis-web/blob/master/app/templates/settings/index.hbs#L19

**Comment by joshk** [comment]
@drogus can you look into this?

**Comment by joshk** [comment]
We have deployed some recent changes to the settings screen which should address the issue you reported.

Thanks a bundle!
