### ISSUE TITLE
Failed build not marked as failure can't be restarted or canceled.

### ISSUE THREAD

**Issue by kaeawc** [travis-ci/travis-web#341]
As seen [here](https://travis-ci.org/kaeawc/testable-active-android/builds/53896680) the build hasn't been marked as failed even though the script definitely exited with a failure status. Sometimes during page load a button to cancel or restart flashes very briefly and then disappears.

**Comment by joshk** [comment]
Thanks for filing the issue. I have fixed the build in question.
Please open further issues on https://github.com/travis-ci/travis-ci/issues
Have a great day.
