### ISSUE TITLE
Unify "errored" state color

### ISSUE THREAD

**Issue by simi** [travis-ci/travis-web#346]
Everything (except the favicon) is red for `errored` state of build (or job) now and the only difference against `failed` state is icon (cross for `failed` vs exclamation mark for `errored`).

In the contrast of `errored` state, `canceled` state is still using gray.

It is easy to use red favicon for `errored` state (probably by changing https://github.com/travis-ci/travis-web/blob/797f746c84110f999b88066c90d4585c8734dce3/app/utils/helpers.coffee#L13).

What's the correct? Red favicon or gray build result colors for `errored` state? I would like to provide PR for this once it will be clarified.

*Actually I was fan of third color for `errored` state, but it will be great to unify this in anyway.*

**Comment by joshk** [comment]
I believe we have fixed this.

I'm closing this for now, if you would like to talk further about this please open a new issue on the main issue tracker.
