### ISSUE TITLE
Consider using a mono-spaced font that isn't the monospace fallback (Courier)

### ISSUE THREAD

**Issue by mnquintana** [travis-ci/travis-web#347]
I love the Travis web client (and especially the new redesign!), but there's one little thing that's always bothered me – the font used for the build logs (currently the monospace fallback - Courier on my system). Courier (and the default monospace fallback on most systems) isn't a very readable font for code / logs, and the web client is already using a non-system font for UI text (Source Sans Pro), so why not change to a more readable webfont? 

Source Code Pro would complement Source Sans Pro nicely, although there are other good options too.

**Original (Courier)**
![screenshot 2015-04-13 07 46 56](https://cloud.githubusercontent.com/assets/823545/7114987/4a855d5e-e1b1-11e4-8b6a-772a2b500ab4.png)

**Source Code Pro**
![screenshot 2015-04-13 07 42 46](https://cloud.githubusercontent.com/assets/823545/7114939/c390a128-e1b0-11e4-9931-564d3faeae06.png)

**Fira Mono**
![screenshot 2015-04-13 07 44 47](https://cloud.githubusercontent.com/assets/823545/7114960/00a314ba-e1b1-11e4-8754-b487b2eb40e6.png)

**Comment by joshk** [comment]
Thanks for opening this, and sorry for the delay.

@saltinejustine @lislis what are your thoughts on Source Code Pro?

**Comment by saltinejustine** [comment]
Hey @mnquintana! Thanks for opening this issue and we're super glad you like the design changes we're making! I really appreciate the consideration you took in recommending Source Sans Code. I'd actually not even heard of it until you pointed it out!

However, @lislis and I have talked it over and we both agreed that loading another web font would damage performance further. So unfortunately we're going to have to decide to leave our current typeface as it is.

But we super-appreciate you opening the issue and making a great point. We hope you have a great day and please let us know of any more UI suggestions/request!
