### ISSUE TITLE
Jobs display reads "Node.js: 0.1" instead of "Node.js: 0.10"

### ISSUE THREAD

**Issue by kemitchell** [travis-ci/travis-web#351]
I'd expect the jobs list to display Node.js 0.10's version as "Node.js: 0.10", but instead it reads "Node.js: 0.1".

![jobs](https://cloud.githubusercontent.com/assets/205760/7485839/791b56c2-f350-11e4-88ef-8854ef752825.png)

To reproduce the issue, create a Travis-enabled repository with a `.travis.yml` like:

```yml
language: node_js
node_js:
  - 0.10
  - node
```

Here is an example build: https://travis-ci.org/kemitchell/spdx.js/builds/61396939

Many thanks for Travis, and congrats on the recent redesign!

K

**Comment by Joshua-Anderson** [comment]
`0.10` is parsed as a float and becomes `0.1`. Adding quotes (`"0.10"`) causes it to be parsed as a string and gives you the expected output. Since this is a common issue, Travis CI aliased node `0.1` to `0.10` but they can't do anything about the UI.

**Comment by kemitchell** [comment]
Thanks, @Joshua-Anderson.

Let this pull request stand as evidence: I'm an idiot, but I'm the kind of idiot who reads CONTRIBUTING.
