### ISSUE TITLE
Inaccurate "Running for" duration

### ISSUE THREAD

**Issue by pglombardo** [travis-ci/travis-web#355]
Not sure if this is a web-side or background worker issue.

If a Build job starts and finishes while there are other un-started jobs pending, the "running for" value gets reset to zero.

For example, this build has been running for about 45 minutes as individual jobs slowly gets processed.  Note that the "running for" value shows 48 seconds.

![screenshot 2015-05-11 19 32 26](https://cloud.githubusercontent.com/assets/395132/7571076/48a2317c-f815-11e4-95da-2b328e1d296b.png)

Is this accurate?  I would think "running for" should reflect the duration of the build with all jobs included.

**Comment by joshk** [comment]
Sorry for the delay in responding.

Are you still seeing this issue?

**Comment by joshk** [comment]
I'm closing this issue for the time being. If you encounter this issue again please open a new issue on the main issue tracker (https://github.com/travis-ci/travis-ci)

Thanks a bundle
