### ISSUE TITLE
Can't access build info for brach build

### ISSUE THREAD

**Issue by akolomiychuk** [travis-ci/travis-web#364]
Hi guys, just want to point an old bug, that is quite annoying for me...

When I push my changes to the branch with pull request
And `branch build` is pass (with any status)
And I'm on current build page (`https://magnum.travis-ci.com/<myteam>/<myrepo>`), which contain `pull request` build for this branch (ex: "Pull Request #487")
Then I see the status, duration and the link of `branch build` on left sidebar.

This works fine, but:
When I click on the link to the `branch build` the page url changes to the `https://magnum.travis-ci.com/<myteam>/<myrepo>/builds/<build-id>` and then immediately blinks back to `https://magnum.travis-ci.com/<myteam>/<myrepo>`.

I expect to go to the `branch build` page instead of that.

Can you guys please take a look and fix it?

Thanks,
Anton

**Comment by BanzaiMan** [comment]
Hi, Anton, sorry to hear about the issue. Could you attach a few screenshot to explain what is happening, and what you expect to happen instead?

**Comment by akolomiychuk** [comment]
Sorry @BanzaiMan , this is actually is not a bug. I just not understood behavior correctly.

I close the issue.
