### ISSUE TITLE
Show net build time in addition to total build time

### ISSUE THREAD

**Issue by mnquintana** [travis-ci/travis-web#365]
Currently, the build view only shows the total build time across all jobs (ie. the sum of each individual job's build time).

It would be awesome if, in addition to this, the build view showed the net build time (ie. the amount of human time the build actually ran for).

For example, take this build: https://travis-ci.org/atom/atom/builds/68996020

Total Build Time (currently shown) | Net Build Time (proposed)
----------------------------------------------|------------------------------------
51 min 24 sec | 21 min 49 sec

**Comment by BanzaiMan** [comment]
Thanks for opening this issue. I believe this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1486.

**Comment by mnquintana** [comment]
@BanzaiMan Ah you're right, sorry about the noise!
