### ISSUE TITLE
Stop using "errored"

### ISSUE THREAD

**Issue by jtdaugherty** [travis-ci/travis-web#373]
The word "error" is not a verb, so "errored" is not a word.  A word that we already have that works well instead is "failed."  Can travis-ci be updated to stop using this convention and use a different word (that is actually a verb) instead?

**Comment by GrahamCampbell** [comment]
Failed and errored are two different cases though.

One means the tests failed, and the other means setup failed.

**Comment by jtdaugherty** [comment]
I don't think there is a generally accepted definition of either, and it depends heavily on context.  But I agree that using different terms for those two things provides a useful distinction.  But no matter what we mean by the terms, "errored" is still made-up. :)

**Comment by jtdaugherty** [comment]
I think a clearer way to say what we mean is to say it explicitly: "setup failed", "tests failed", etc.

**Comment by GrahamCampbell** [comment]
It has to be error or failure I'm afraid. https://developer.github.com/v3/repos/statuses/

**Comment by jtdaugherty** [comment]
How does GitHub's API affect the language that Travis-CI uses in e-mails and on its web site?  For example, I got an e-mail saying my build had "errored", but surely that can be changed no matter what GitHub does.

**Comment by GrahamCampbell** [comment]
I don't mind that word. It's commonly used across all github intgerations.

**Comment by joshk** [comment]
Thank you for starting this discussion; I didn't realize all this. Although `errored` is not a word recognized by the Oxford Dictionary, it has become a convention within the Travis and CI community as meaning something which has stopped the build before tests were able to run.

I am going to close this issue for the time being as I think our use of the word is ahead of its time. :wink:

**Comment by svenfuchs** [comment]
Also, I'd tend to think Merriam-Webster should be good enough a reference, too? http://nws.merriam-webster.com/opendictionary/newword_display_alpha.php?letter=Er&last=10

But yeah, we're using it in a pretty context/domain-specific meaning.
