### ISSUE TITLE
Build not starting instantaneously after adding cache option

### ISSUE THREAD

**Issue by OrkoHunter** [travis-ci/travis-web#376]
I recently switched a repo to container-based env and the build used to start instantaneously (Wow!).

But today I added the option of caching pip wheel, and now it is taking forever to start. (1 hour passed)

Here is the link to the build log https://travis-ci.org/OrkoHunter/networkx-metis/builds/71538227

**Comment by joshk** [comment]
Thanks for creating the issue.

I checked our DB and the jobs were cancelled by the build was stuck in 'created'. You can restart the build and it should start straight away.

Closing this issue for now.

Have a great weekend.
