### ISSUE TITLE
Removed repos are shown

### ISSUE THREAD

**Issue by neomerx** [travis-ci/travis-web#378]
Profile page (e.g. https://travis-ci.org/neomerx/ ) for logged out visitors shows removed repos (which existed in the past but don't exist anymore). Also page title is 'null - null - Travis CI' which also looks as an error.

**Comment by neomerx** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/10420662/8799666/6aaac014-2fb4-11e5-8560-92360d194186.png)

**Comment by joshk** [comment]
Thank you for creating this issue.

We are a fix in the works for this.

In the mean time, can you please create this issue on https://github.com/travis-ci/travis-ci/issues

**Comment by neomerx** [comment]
not yet fixed bug closed? :trollface:
