### ISSUE TITLE
Suggestion: Alternative Project View which shows all projects and branches

### ISSUE THREAD

**Issue by dougthor42** [travis-ci/travis-web#380]
I find that the user Project View ([example](https://travis-ci.org/dougthor42)) lacks information.

![image](https://cloud.githubusercontent.com/assets/5386897/8861121/3a485596-313d-11e5-8dc1-7e8179c07947.png)

Specifically, a user cannot see all branches of all projects at once.

I propose adding an alternate view which fixes this. I've included a (very crude) mockup - a simple grid view where columns are various projects, and rows are their branches:

![image](https://cloud.githubusercontent.com/assets/5386897/8861578/09066948-3140-11e5-9122-1a431cd3c63e.png)

As you can see, all the same information is still there (Build #, Commit #, duration, end_time, status via color), but now we can see all branches. It would also be nice if the user could transpose the matrix, for those times when users have many more projects than they do branches.

Another example would be [BuildBot](http://buildbot.net/)'s [grid display](http://buildbot.wxpython.org:8010/grid), however this is only for one project at a time.

I was thinking of trying to do this myself within a standard webpage, but I've so far been unable to find any API that I could use to grab a user's (my) projects and branches.

I also don't know Ruby or Ember CLI, so I'm afraid that I won't be able to help with the coding :worried:.

**Comment by joshk** [comment]
Hi @dougthor42 

Thanks for the feature request, especially the time and effort you have taken in explaining what it is you would like.

We are in the process of finishing and improving the 'owner' page, which you referenced in the first screen shot. We don't expect major changes to the design, but I would like to add some extra information to each 'repo' line.

I'm sorry but we don't have plans to add this sort of UI to the 'owner' page as the edge cases for the majority of users will limit the use of this sort of addition.

What I would fully recommend though is using our API to build the UI view you would like to use.

Thank you very much for the awesome feedback and suggestion.

Josh
