### ISSUE TITLE
The column for "env" should grow to show more variables

### ISSUE THREAD

**Issue by briansmith** [travis-ci/travis-web#381]
See this annotated screen shot:

![image](https://cloud.githubusercontent.com/assets/16816/8884601/0643f8ce-3226-11e5-8949-a7039cead2e1.png)

A simple, big, and much-appreciated improvement would be to change the CSS for the table so that the "env" column gets all the extra space when the table is resized.

**Comment by saltinejustine** [comment]
Hey @briansmith,

thanks for opening this issue and taking the time to note up a screen shot.

I'm going to have a talk with our wonderful front-end developer @lislis and she and I can discuss what we can do in the constraints of our responsive framework and address this UX problem you're having.

Have a great day!

**Comment by joshk** [comment]
Hey @briansmith 

We have some major UI changes in the works, which will affect the available space in the job list. I'm going to close this issue for the time being.

Thank you for taking the time to open this and give this great feedback.

Josh
