### ISSUE TITLE
Workspace Viewer / Browser for Jobs

### ISSUE THREAD

**Issue by guikeller** [travis-ci/travis-web#383]
Hello guys,

I have created this issue a couple of days ago: https://github.com/travis-ci/travis-ci/issues/4551
But I believe that it suits here best as it's a front-end feature request.

Thank you very much in advance.

Kind regards,
Gui

**Comment by joshk** [comment]
I'm sorry but the proper place for these requests is on the original repo that you opened it on.

I'm closing this issue in favor of the original one.

Thanks a bundle

Josh

**Comment by guikeller** [comment]
Hi Josh,

I understand that you guys are busy but it'd be nice to hear something back as it has been almost two weeks since I have opened up the issue.

Thank you very much in advance.

Kind regards,
Gui

**Comment by joshk** [comment]
Hi @guikeller 

I'm sorry, but I am in NZ at the moment due to some urgent family matters.

We will be in touch soon, please be patient.

Thanks

Josh

**Comment by guikeller** [comment]
Hi @joshk,

Sorry to hear about that man, hope it all turns out well with the family.
And welcome back to New Zealand ;)

Kind regards,
Gui
