### ISSUE TITLE
Incorrect output when re-building a build

### ISSUE THREAD

**Issue by alexlafroscia** [travis-ci/travis-web#385]
I've been trying to re-run a build today and noticed a weird error.  It seems like the output from the previous build is sticking around for the new build.

Here is a [gist of the output that I saw](https://gist.github.com/alexlafroscia/16da49861547035cd0dd).

For example, you can see that [line 171](https://gist.github.com/alexlafroscia/16da49861547035cd0dd#file-output-txt-L171) has the output of the re-run, where the tests all pass.  However, [line 286](https://gist.github.com/alexlafroscia/16da49861547035cd0dd#file-output-txt-L286) has the old test results, where it was all failures.

If it's helpful at all, the repo in question is [this one](https://travis-ci.org/alexlafroscia/vim-ember-cli).  It seems like even now, it's showing the wrong output; while the build is marked as passing, and the output in the gist shows the tests passing, the output at that link shows the results from a previous, failing build.

**Comment by lislis** [comment]
Hello @alexlafroscia and thanks for opening the ticket! We're currently trying to collect all issues in a central repository and close the other issue trackers.
Please open a ticket here: https://github.com/travis-ci/travis-ci/issues
Thank you!
