### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-web#387]
I was trying to understand what exactly this repo does - and I felt that the README doesnt give much info about it.
There should be a slightly non technical explanation ...

Does this repo use ember + coffeescript to render a web client through which it is easy to view travis builds ? If I wish to can I use the same code (with modifications) to run for example a CI web service which simply runs "pylinter" in my server ?

**Comment by lislis** [comment]
Hello @AbdealiJK and thank you for opening a ticket!
We are currently cleaning up our issue trackers in favour of a single, central one. 
Please open a ticket here: https://github.com/travis-ci/travis-ci/issues
Thank you in advance!
I will close this one now.
