### ISSUE TITLE
Async flash messages should have a "loading ..." shell message

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-web#56]
When one uses the "requeue build" function then the request goes to the api and returns with a flash message that we then display.

When this request takes a bit one might be confused for a second and think that nothing has happened, thus retry (actually happens to me on staging when api takes a while to spin up the app).

I think we should extend the flash message thing generically (i.e. for this usecase as well as whatever flash messages we add in future) so that it displays a "shell" flash message immediately that has the "loading ..." spinner and indicates that something is happening. So we'd "expect" an actual flash message. As soon this message comes back we'd replace the shell or fill it in.

Wdyt?

**Comment by joshk** [comment]
Closing as this is stale
